### ISSUE TITLE
Footer "Link Úteis" dont scroll up when clicked

### ISSUE THREAD

**Issue by muriloqr** [MateusAbdala/nicole-makeup-angular#1]
Footer "Link Úteis" dont scroll up when clicked, it's a bad user experience.

**Comment by MateusAbdala** [comment]
Hi @muriloqr, I will work on that, don't worry.

**Comment by MateusAbdala** [comment]
Hello again @muriloqr , please check `ScrollToDirective`. I think this is a great solution. If you find something wrong with this, i will reopen the problem.
